Switch keppel.global for container images
sapcc/kubernikus pull request #649
Opened 2022-04-21 14:55 UTC by Nuckal777

2022-04-22 10:07 UTC, databus23 approved these changes

2022-04-22 10:09 UTC, databus23 commented
One last thought. Is this affecting the keppel image garbage collection. Like does gatekeeper still prevent keppel do gc images that are in active use in the cluster? @majewsky

2022-04-22 11:01 UTC, majewsky commented
Good thought, but it does not. GC policies are evaluated on the primary account in eu-de-1. Since we aggregate last-pulled events from the replica accounts into the primary, it does not matter where the image is pulled exactly.

2022-11-03 16:02 UTC, databus23 requested changes
In adding to switching to keppel.global we should also switch to prober keppel mirrors for registry.k8s.io

2022-11-21 13:19 UTC, Nuckal777 commented
Closing in favor of #719 .

2022-11-21 13:19 UTC, closed without merging