Containerd config injector
sapcc/kubernikus pull request #841
Opened 2023-10-26 05:08 UTC by xsen84

Containerd startup config is modified by adding extra options:
sandbox_image = "{{ .PauseImage }}:{{ .PauseImageTag }}"
enable_unprivileged_ports = true
enable_unprivileged_icmp = true
This is done via xtoml binary

2023-11-07 13:54 UTC, Nuckal777 commented
Do we run into issues when https://repo.eu-de-1.cloud.sap/xtoml/xtoml is unreachable due to issues in the metal controlplane, so that metal nodes cannot be created/rebooted anymore?

2023-11-21 13:44 UTC, databus23 commented
@xsen84 Can you comment of @Nuckal777's remark. Can we live with a swift dependency for bootstrapping on-metal nodes. cc @SchwarzM

2023-11-22 15:18 UTC, databus23 commented
Discussed this in out kubernetes weekly and agreed to change this PR to pull the binary via a docker image from keppel.global similar to how we do it for the kubelet. This avoid adding a hard dependency to swift in eu-de-1 from all regions

2023-11-22 15:19 UTC, databus23 requested changes
Please update the PR according to my last comment. Thanks!

2023-11-24 09:00 UTC, xsen84 commented
@databus23 
with the docker image approach I hit another issue:

- `containerd` service needs to start after the `config_replace` service,
- `config_replace` service needs `docker` service  to pull the image with the binary,
- `docker` service needs `containerd` service

... and all this causes a dependency loop

> minion-4c07d928741c ~ # systemctl status docker
> ○ docker.service - Docker Application Container Engine
>      Loaded: loaded (/run/systemd/system/docker.service; enabled; preset: enabled)
>     Drop-In: /etc/systemd/system/docker.service.d
>              └─20-docker-opts.conf
>      Active: inactive (dead)
> TriggeredBy: × docker.socket
>        Docs: http://docs.docker.com
> 
> Nov 24 08:24:16 minion-4c07d928741c.cc.qa-de-1.cloud.sap systemd[1]: docker.service: Found dependency on docker.service/start
> Nov 24 08:24:16 minion-4c07d928741c.cc.qa-de-1.cloud.sap systemd[1]: docker.service: Job containerd.service/start deleted to break ordering cycle starting with docker.service/start
> Nov 24 08:24:17 minion-4c07d928741c.cc.qa-de-1.cloud.sap systemd[1]: containerd-config-replace.service: Found ordering cycle on docker.service/start
> Nov 24 08:24:17 minion-4c07d928741c.cc.qa-de-1.cloud.sap systemd[1]: containerd.service: Unable to break cycle starting with containerd.service/start


a possible solution would be to restart the containerd service once we got the desired containerd config in place:

> [Unit]
> Description=Modify startup configuration file of containerd
> After=network-online.target docker.service
> Wants=network-online.target
> [Service]
> User=root
> WorkingDirectory=/opt/bin/
> ExecStartPre=docker run --rm -v /opt/bin:/opt/bin keppel.global.cloud.sap/ccloud/xtoml:v1.0.0 cp /usr/local/bin/xtoml /opt/bin/
> ExecStart=/opt/bin/containerd-config-replace.sh
> ExecStartPost=systemctl daemon-reload
> ExecStartPost=systemctl restart containerd
> [Install]
> WantedBy=multi-user.target

it works, but is not quite nice

i open for suggestions

2023-11-29 12:03 UTC, xsen84 commented
using

```https://repo.{{ .OpenstackRegion }}.cloud.sap/controlplane/xtoml/xtoml```

 to download binary
 change is already deployed  in qa-de-1  apod/virtual

2023-11-29 14:58 UTC, jknipper approved these changes

2023-11-29 14:58 UTC, jknipper approved these changes

2023-11-29 15:29 UTC, databus23 approved these changes

2023-11-29 15:33 UTC, merged